### PR TITLE
Pivnet capybara templates

### PR DESCRIPTION
**Pull request by squeedee**
Adds `sos` and `sop` live templates for capybara.

### CODE REVIEW

**Comment by moonmaster9000** [comment]
Thanks! It looks there's still quite a few files either with "Metrix" in the name or that reference "metrix_pivotal_ide_prefs" in the source XML...

**Comment by squeedee** [comment]
Honestly I don'y know how those commits got into my pull request. i only wanted to merge 625d91a

**Comment by squeedee** [comment]
going to remake this pull request

**Comment by squeedee** [comment]
I worked out what's going on. looks like we're pulling from the pivotal-cf master branch not this one.

**Pull request closed without merging**
